//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FinalAssignmentCS.ReaderService {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ReaderService.IReader")]
    public interface IReader {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IReader/GetProducts", ReplyAction="http://tempuri.org/IReader/GetProductsResponse")]
        System.Data.DataSet GetProducts();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IReader/GetProducts", ReplyAction="http://tempuri.org/IReader/GetProductsResponse")]
        System.Threading.Tasks.Task<System.Data.DataSet> GetProductsAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IReader/GetUsers", ReplyAction="http://tempuri.org/IReader/GetUsersResponse")]
        System.Data.DataSet GetUsers();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IReader/GetUsers", ReplyAction="http://tempuri.org/IReader/GetUsersResponse")]
        System.Threading.Tasks.Task<System.Data.DataSet> GetUsersAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IReader/GetAddress", ReplyAction="http://tempuri.org/IReader/GetAddressResponse")]
        System.Data.DataSet GetAddress();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IReader/GetAddress", ReplyAction="http://tempuri.org/IReader/GetAddressResponse")]
        System.Threading.Tasks.Task<System.Data.DataSet> GetAddressAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IReader/GetPaymentInfo", ReplyAction="http://tempuri.org/IReader/GetPaymentInfoResponse")]
        System.Data.DataSet GetPaymentInfo();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IReader/GetPaymentInfo", ReplyAction="http://tempuri.org/IReader/GetPaymentInfoResponse")]
        System.Threading.Tasks.Task<System.Data.DataSet> GetPaymentInfoAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IReader/GetOrders", ReplyAction="http://tempuri.org/IReader/GetOrdersResponse")]
        System.Data.DataSet GetOrders();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IReader/GetOrders", ReplyAction="http://tempuri.org/IReader/GetOrdersResponse")]
        System.Threading.Tasks.Task<System.Data.DataSet> GetOrdersAsync();
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IReaderChannel : FinalAssignmentCS.ReaderService.IReader, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class ReaderClient : System.ServiceModel.ClientBase<FinalAssignmentCS.ReaderService.IReader>, FinalAssignmentCS.ReaderService.IReader {
        
        public ReaderClient() {
        }
        
        public ReaderClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public ReaderClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ReaderClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ReaderClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public System.Data.DataSet GetProducts() {
            return base.Channel.GetProducts();
        }
        
        public System.Threading.Tasks.Task<System.Data.DataSet> GetProductsAsync() {
            return base.Channel.GetProductsAsync();
        }
        
        public System.Data.DataSet GetUsers() {
            return base.Channel.GetUsers();
        }
        
        public System.Threading.Tasks.Task<System.Data.DataSet> GetUsersAsync() {
            return base.Channel.GetUsersAsync();
        }
        
        public System.Data.DataSet GetAddress() {
            return base.Channel.GetAddress();
        }
        
        public System.Threading.Tasks.Task<System.Data.DataSet> GetAddressAsync() {
            return base.Channel.GetAddressAsync();
        }
        
        public System.Data.DataSet GetPaymentInfo() {
            return base.Channel.GetPaymentInfo();
        }
        
        public System.Threading.Tasks.Task<System.Data.DataSet> GetPaymentInfoAsync() {
            return base.Channel.GetPaymentInfoAsync();
        }
        
        public System.Data.DataSet GetOrders() {
            return base.Channel.GetOrders();
        }
        
        public System.Threading.Tasks.Task<System.Data.DataSet> GetOrdersAsync() {
            return base.Channel.GetOrdersAsync();
        }
    }
}
